//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LibraryStats", Namespace="http://schemas.datacontract.org/2004/07/LibraryManagement.Presentation.WebAPI.SOA" +
        "P")]
    public partial class LibraryStats : object
    {
        
        private int ActiveLoansCountField;
        
        private int BooksCountField;
        
        private int ReadersCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveLoansCount
        {
            get
            {
                return this.ActiveLoansCountField;
            }
            set
            {
                this.ActiveLoansCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BooksCount
        {
            get
            {
                return this.BooksCountField;
            }
            set
            {
                this.BooksCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReadersCount
        {
            get
            {
                return this.ReadersCountField;
            }
            set
            {
                this.ReadersCountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapReference.ILibraryStatsService")]
    public interface ILibraryStatsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryStatsService/GetLibraryStats", ReplyAction="http://tempuri.org/ILibraryStatsService/GetLibraryStatsResponse")]
        System.Threading.Tasks.Task<SoapReference.LibraryStats> GetLibraryStatsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ILibraryStatsServiceChannel : SoapReference.ILibraryStatsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class LibraryStatsServiceClient : System.ServiceModel.ClientBase<SoapReference.ILibraryStatsService>, SoapReference.ILibraryStatsService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LibraryStatsServiceClient() : 
                base(LibraryStatsServiceClient.GetDefaultBinding(), LibraryStatsServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILibraryStatsService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryStatsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LibraryStatsServiceClient.GetBindingForEndpoint(endpointConfiguration), LibraryStatsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryStatsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LibraryStatsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryStatsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LibraryStatsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryStatsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SoapReference.LibraryStats> GetLibraryStatsAsync()
        {
            return base.Channel.GetLibraryStatsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILibraryStatsService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILibraryStatsService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7007/LibraryStats.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LibraryStatsServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILibraryStatsService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LibraryStatsServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILibraryStatsService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ILibraryStatsService,
        }
    }
}
